global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'core'
    static_configs:
            - targets: ['209.97.148.231:4000', '45.55.47.24:4000', '68.183.48.203:4000']
